display_name: 局域网给我
packager: ynzj
packagerEmail: 927070135@qq.com
url: https://gitee.com/ynzj/juyuwanggeiwo
buildArch: x86_64
license: Apache-2.0

icon: assets/img/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: An open source cross-platform alternative to AirDrop
summary: 局域网传输 · 跨平台互传 · 断点续传（基于 LocalSend 协议二次开发）
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
